name: ci-fullstack-workflow

# Ensure the workflow runs on schedule (Sunday at 0:00) and on push to the main branch
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0'
  

#Use a matrix strategy to use Node.js versions 16.x and 18.x
jobs:
  build-test-lint:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
      # Check out the code from the repository.
      - name: Checkout code
        uses: actions/checkout@v3
      # Set up a Node.js environment using the specified node version.
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          
      # ----------------------
      # Backend
      # ----------------------
      - name: Install backend dependencies
        working-directory: ./backend
        run: npm ci

      - name: Lint backend
        working-directory: ./backend
        run: npm run lint

      - name: Test backend
        working-directory: ./backend
        run: npm test --if-present

      - name: Build backend
        working-directory: ./backend
        run: npm run build --if-present

      # Send a console message at completion.
      - run: |
          echo "Hello ${{github.actor}}. You pushed to ${{github.repository}} at $(date)."

        
